"""empty message

Revision ID: 3e227a1a1dcc
Revises: 
Create Date: 2021-04-09 15:00:01.663702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e227a1a1dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=False),
    sa.Column('stoptime', sa.DateTime(), nullable=False),
    sa.Column('bikeid', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('from_station_name', sa.String(length=150), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_name', sa.String(length=150), nullable=False),
    sa.Column('user_type', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=150), nullable=True),
    sa.Column('birthday', sa.String(length=150), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
